### PR TITLE
Fix editing of draggable blocks in Safari

### LINKED ISSUE #2612: Unable to type in text blocks in Safari
When in Safari - all text blocks do not display text when typing, and do not update from the helper text.

This is not impacting the "code" block, however.

### PR DESCRIPTION
**Pull request by kienstra**
# Before
As @MackenzieHartung pointed out in #2612, it wasn't possible to type in any `[draggable]` element in Safari, meaning the Text block wasn't usable.

# After
This uses @miina's idea of `-webkit-user-select` for the `[draggable]` element that wraps the blocks.

This fixed the issue in Safari, at least in brief testing. Dragging also still works in Chrome and Firefox, after quick testing.

Fixes #2612

### CODE REVIEW

**Comment by kienstra** [comment]
**Request For Review**

Hi @swissspidy,
Could you please review this? Thanks, I know it's late.

**Comment by kienstra** [comment]
Hm, it looks like in Safari, the Text block doesn't drag if the text isn't highlighted.

**Comment by swissspidy** [comment]
Travis failure is an unrelated hiccup, can be ignored.

**Comment by kienstra** [comment]
This might be related to this:
https://stackoverflow.com/questions/21680363/prevent-drag-event-to-interfere-with-input-elements-in-firefox-using-html5-drag

**Comment by kienstra** [comment]
This might be related:
https://github.com/react-dnd/react-dnd/issues/178#issuecomment-192021227

**Comment by miina** [comment]
Not sure if we should merge this and then look into the dragging issue separately? Thoughts, @swissspidy?

@kienstra Did you have any new findings for the dragging issue meanwhile?

**Comment by swissspidy** [comment]
Looking at the link that Ryan sent, we might need to test possible differences between using `-webkit-user-select: auto;` and `user-select: text;`.

Getting this one into 1.2 is better than having no fix at all.

**Comment by miina** [comment]
> Looking at the link that Ryan sent, we might need to test possible differences between using -webkit-user-select: auto; and user-select: text;.

Seems to have the same result, using either of these.

**Comment by miina** [comment]
@swissspidy Could you test if dragging and selecting both work for you now in Safari?

**Comment by swissspidy** [comment]
It does work like a charm 😍

Tested all text-based blocks with no issues.

**Pull request merged**
