### PR TITLE
Remove width restriction from template preview resizer.

### LINKED ISSUE #2574: Template thumbnails not appearing as intended in + menu
When accessing the + menu to insert a template, the template thumbnails contain unexpected text styles, see image below:

Screen Shot 2019-06-12 at 5 51 27 AM

Expectation is that the text styles would match what is being inserted...use the "tip" template to recreate issue...when inserted, text appears in a different style than it does in the thumbnail.

### PR DESCRIPTION
**Pull request by miina**
Fixes #2574.

### CODE REVIEW

**Comment by swissspidy** [comment]
I'm not sure if this fully resolves the issue

The tip block is not centered:

Screenshot 2019-06-12 at 12 13 00

The CTA blocks in the previews are also not centered:

Screenshot 2019-06-12 at 12 13 25

**Comment by miina** [comment]
Hmm, weird, I'm seeing everything as expected:
Screenshot 2019-06-12 at 12 16 07

Screenshot 2019-06-12 at 12 16 32

Will check why it's showing OK for me. Perhaps something didn't load properly.

**Comment by miina** [comment]
@swissspidy Could you check again if you see it OK now? Looks like the PR wasn't updated to the latest `develop`.

**Comment by swissspidy** [comment]
Much better now! Thanks 🎉

**Pull request merged**
