### PR TITLE
Fix inserter menu style.

### LINKED ISSUE #2576: Template Inserters menu styling displays incorrectly sometimes
Sometimes, depending on the vertical scrolling on the page, the template inserter's styling looks a bit odd:

Screenshot 2019-06-12 at 12 35 00

### PR DESCRIPTION
**Pull request by miina**
Fixes #2576.

### CODE REVIEW

**Comment by swissspidy** [comment]
If I only knew how to reproduce the issue 🤔 🤷‍♂ 

Any tips?

**Comment by miina** [comment]
If you scroll up as much as possible while the Template Inserter is open then it should show. My screen is 13 inches, not sure if this influences testing for you.

Perhaps you can try on `develop` to see if the issue appears while scrolling up, potentially reducing the window size accordingly?

**Comment by swissspidy** [comment]
I remember seeing the issue in the past, but not at the moment. Maybe someone else though? / cc @westonruter @kienstra

**Comment by miina** [comment]
Hmm, OK.

Adding gif-s to reflect the issue. Before:
Jun-12-2019 18-32-32

After:
after

**Pull request merged**
