### PR TITLE
Fix italic and bold for amp-fit-text

### LINKED ISSUE #2342: Setting Text block as bold/italic causes unexpected shift
If I add a Text block and increase its height like so:

image

Upon selecting Bold or Italic, the text shifts up unexpectedly:

image

image

Removing the formatting causes the expected position to be restored.

### PR DESCRIPTION
**Pull request by miina**
Fixes #2342.

- Adjust style so that using italic and bold doesn't break the text into multiple lines in case of using amp-fit-text (props @mehigh).
- Adjust resizing and class names accordingly.

### CODE REVIEW

**Comment by mehigh** [comment]
👍  I'm OK to contribute this.

@miina I've sent a PR against this branch from our fork as I don't have push access to this repo:
https://github.com/ampproject/amp-wp/pull/2499

**Comment by swissspidy** [comment]
Two things I just spotted:

When creating a new story, the placeholder's position of the initial text block is broken:

Screenshot 2019-06-04 at 14 43 31

Second, block styles don't work anymore when fit-text is on. See frontend vs. editor comparison here:

Screenshot 2019-06-04 at 14 45 35
Screenshot 2019-06-04 at 14 45 38

**Comment by swissspidy** [comment]
When I turn off amp-fit-text on above's block, it looks like this on the frontend:

Screenshot 2019-06-04 at 14 48 03

That's because of the `.amp-story-block-wrapper > p` selector declaring `display: flex`.

**Comment by swissspidy** [comment]
NB: `npm run lint:css:fix` should be able to fix the stylelint errors.

**Comment by miina** [comment]
Thanks for testing, @swissspidy. The issues should be fixed now!

Props @mehigh for e9b67d3.

**Comment by swissspidy** [comment]
> The bad news is that it appears that one or more commits were authored or co-authored by someone other than the pull request submitter. We need to confirm that all authors are ok with their commits being contributed to this project. Please have them confirm that here in the pull request.

Looks like that refers to the commit by @mehigh. Can you confirm that? 🙂 And perhaps double check whether you signed that CLA.

**Comment by miina** [comment]
> Looks like that refers to the commit by @mehigh. Can you confirm that? 🙂 And perhaps double check whether you signed that CLA.

Yes, confirmed that it's Mike's commits and he already confirmed being OK contributing to the PR: https://github.com/ampproject/amp-wp/pull/2494#issuecomment-498421196

Also, we both have CLA-s signed. Otherwise, all my contributions would complain :D

**Comment by swissspidy** [comment]
Ah, missed that comment. All good then 🙂

**Pull request merged**
