### PR TITLE
Replace wrapperClassName usage

### LINKED ISSUE #3576: Deprecated `wrapperClassName` warning in console
## Bug Description

There is a deprecated `wrapperClassName` warning in console which is not causing issues yet but would cause after getting removed.

`wp.blockEditor.RichText wrapperClassName prop is deprecated. Please use className prop or create your own wrapper div instead.`

See also https://github.com/WordPress/gutenberg/pull/17713 where the deprecation was added.

## Expected Behaviour

There should be no deprecated warning messages in console.

We’re using both `className` and `wrapperClassName` prop [in some cases](https://github.com/ampproject/amp-wp/search?utf8=%E2%9C%93&q=wrapperClassName&type=) so we will probably need to create a wrapper `div` instead of using `wrapperClassName`. 

## Steps to reproduce

1. Activate Gutenberg 6.7
1. Create new story
1. Add text block
1. Try to edit the text
1. See the warning in the console

## Screenshots

Screenshot 2019-10-21 at 15 46 22

## Additional context

 - WordPress version: 5.3
 - Plugin version: `develop`
 - Gutenberg plugin version (if applicable): 6.7
 - AMP plugin template mode:
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* There should be no console warnings related to `wrapperClassName` when using the stories editor + Gutenberg 6.7

## Implementation brief

* Look through all the [cases](https://github.com/ampproject/amp-wp/search?utf8=%E2%9C%93&q=wrapperClassName&type=) where we are using `wrapperClassName` and replace it with `className` where possible, or remove `wrapperClassName` prop and add a wrapper `div` with the class name taken from the previous `wrapperClassName` instead. E.g. instead of 
```
<RichText
	....
	wrapperClassName="amp-story-page-attachment__text"
	....
/>
```
add something like
```
<div className="amp-story-page-attachment__text"
    <RichText
	....
    />
</div>
```
* Since we are using `wrapperClassName` and `className` both at least in some cases then it's likely that we'll need to create our own wrapper div to replace it.
* Ensure that the interface for the user remains the same, adjust the CSS if not.
* The change might potentially influence dragging / resizing / dynamic font adjusting, so we need to make sure that after replacing the prop, everything continues to work as expected for the influenced blocks.

## QA testing instructions

1. Create new story
1. Add text block
1. Try to edit the text
1. Verify there is no warning in the console

## Demo

N / A

## Changelog entry

* Improved compatibility with the latest version of Gutenberg

### PR DESCRIPTION
**Pull request by miina**
## Summary

Fixes #3576 
Replaces deprecated `wrapperClassName` where used.

## Checklist

- [x] My pull request is addressing an [open issue](https://github.com/ampproject/amp-wp/contributing/project-management.md#life-of-an-issue) (please create one otherwise).
- [ ] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/contributing/engineering.md#tests).
- [x] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/contributing/engineering.md) (updates are often made to the guidelines, check it out periodically).

### CODE REVIEW

**Comment by swissspidy** [comment]
@miina The page attachment class names are used in two e2e tests which are now failing

**Comment by miina** [comment]
Hmm, that's odd, can't see this issue, tested before, too. Does it show as expected on `develop` for you?

**Comment by swissspidy** [comment]
Yes, on `develop` it looked fine.

**Comment by miina** [comment]
Could you check if it works OK now? Still couldn't reproduce the issue locally, however, made some changes to match the previous source exactly. Perhaps now it works as expected.

**Comment by swissspidy** [comment]
It does work now 👍 

Screenshot 2019-10-29 at 00 14 24

**Pull request merged**
