### PR TITLE
Refactoring and improving validation error handling

### LINKED ISSUE #2127: Block-level warnings for validation errors fail to update without user interaction
In the editor, when adding one block that has validation errors, the global warning for the post shows up immediately upon saving, but the warning for the specific block does not:

> image

However, upon hovering over the offending block then the warning immediately pops into view:

> image

It seems that the change to the store did not get propagated to the block, so it takes another mutation to the block (e.g. selecting it) to cause it to see the changes.

This likewise happens when the validation error has been fixed. Upon saving the post, the warning sticks around until the block is interacted with again:

> image

Upon hovering over the toolbar, the warning then disappears:

> image

### PR DESCRIPTION
**Pull request by swissspidy**
An attempt to reorganize the block validation and block editor scripts in order to further streamline the block editor integration.

Uses data stores to read and write necessary information, and then `withSelect` to ensure any validation errors are immediately shown without having to interact with the blocks.

While restructuring the code for that I stumbled upon many parts that could be simplified or even completely removed because they were not actually used at all.

Demo: https://cloudup.com/c00a-dLj555

Fixes #2127.
Iterates on #1298.

### CODE REVIEW

**Comment by westonruter** [comment]
IT IS A THING OF BEAUTY.

**Comment by westonruter** [comment]
I'm getting an error on the Validated URL screen:

image

Also getting a JS error when viewing details of a single validation error:

image

**Comment by westonruter** [comment]
I got a JS error when I:

1. Switched to Native mode.
2. Added an AMP Timeago block to a post
3. Switched to Transitional mode
4. Tried to edit the post with the AMP Timeago block

```
TypeError: Cannot read property 'title' of undefined
    at https://wordpressdev.lndo.site/content/plugins/gutenberg/build/block-editor/index.js?ver=1557784482:55:114803
    at t.value (https://wordpressdev.lndo.site/content/plugins/gutenberg/build/block-editor/index.js?ver=1557784482:55:109706)
    at finishClassComponent (https://wordpressdev.lndo.site/content/plugins/gutenberg/vendor/react-dom.165d5c53.js:14830:31)
    at updateClassComponent (https://wordpressdev.lndo.site/content/plugins/gutenberg/vendor/react-dom.165d5c53.js:14785:24)
    at beginWork (https://wordpressdev.lndo.site/content/plugins/gutenberg/vendor/react-dom.165d5c53.js:15733:16)
    at performUnitOfWork (https://wordpressdev.lndo.site/content/plugins/gutenberg/vendor/react-dom.165d5c53.js:19401:12)
    at workLoop (https://wordpressdev.lndo.site/content/plugins/gutenberg/vendor/react-dom.165d5c53.js:19441:24)
    at renderRoot (https://wordpressdev.lndo.site/content/plugins/gutenberg/vendor/react-dom.165d5c53.js:19524:7)
    at performWorkOnRoot (https://wordpressdev.lndo.site/content/plugins/gutenberg/vendor/react-dom.165d5c53.js:20431:7)
    at performWork (https://wordpressdev.lndo.site/content/plugins/gutenberg/vendor/react-dom.165d5c53.js:20343:7)
```

**Comment by swissspidy** [comment]
Awesome, thanks a lot for testing! 🙂 😊 🎉 

Looks like some variables haven't been properly exported. Probably happened sometime during an earlier webpack config rewrite. Should be an easy fix.

That AMP Timeago block issue looks a bit more interesting. The error message doesn't seem to reveal much.

**Comment by swissspidy** [comment]
> I got a JS error when I ...

Hmm, this might have to do with the way blocks are registered and then unregistered again when not using native AMP.

I just tested this, and the timeago block was simply not visible at all (I expected a "this block is invalid" message). The crash only occurred once I tried switching to code editor.

**Comment by swissspidy** [comment]
I just pushed e95bc4176ab32e09d361036edf376e10dfc40e1d which fixes the issue you have had with the JS error, by basically restoring the behavior from `develop`.

By the way, while doing this modernization I also fixed a few bugs with the existing code. For example, after filtering error types you no longer get an AYS dialog when navigating away from the page (since one did not make any changes).

The filter:

Screenshot 2019-05-14 at 15 35 49

**Comment by westonruter** [comment]
I'm still seeing the JS error for the AMP Timeago block existing in the content, when the block is not registered. But it is only happening now when hovering over the block:

image

**Comment by westonruter** [comment]
Shouldn't it rather show this?

image

**Comment by swissspidy** [comment]
> Shouldn't it rather show this?

Yes it should. Can you please test again?

**Comment by westonruter** [comment]
Much better:

image

**Comment by swissspidy** [comment]
According to Travis there is a test failure:

```
There was 1 failure:
1) Test_AMP_Post_Meta_Box::test_enqueue_block_assets

Failed asserting that true is false.

/tmp/wordpress/src/wp-content/plugins/amp/tests/test-class-amp-meta-box.php:91
```

However, locally all the `Test_AMP_Post_Meta_Bo` tests pass for me.

**Comment by westonruter** [comment]
It passes for me locally as well. I'll debug that.

**Comment by westonruter** [comment]
@swissspidy ok, build fixed now. Feel free to merge when you're happy.

**Comment by swissspidy** [comment]
Awesome, thanks a lot!

There's one issue left that I have just noticed. `amp-editor-blocks.js` needs to be loaded for the story editor as well (adds some things like AMP settings to blocks), yet it should not load `amp-block-editor.js` (adds some unwanted things that do not apply to stories at all).

Will need to shuffle some stuff around for that.

**Pull request merged**
