### PR TITLE
Improve handling of Stories in Compatibility Tool

### PR DESCRIPTION
**Pull request by westonruter**
In #3321 it was discovered that rejecting the sanitization of a validation error on an AMP Story results in an infinite redirect when a site is not in Standard mode. When processing a Story, it should behave as if the site is in Standard mode. No redirection should be performed when there are rejected validation errors, but rather the `amp` attribute should be removed from the page to prevent it from being validated as a valid AMP page.

In the same way, when a Story is listed among the Validated URLs in the admin, there should be no `?amp` appearing in the displayed URLs.

Testing instructions:

1. Set mode to Transitional.
2. Create a Story and add a Custom HTML block with some invalid AMP markup, like `<script>bad</script>`
3. Publish Story.
4. A warning message should appear about validation errors. Click “Review Issues”.
5. With this ifx applied, the Validated URL screen should not show `?amp` in the heading.
5. On the Validated URL screen, set the validation error status as “Rejected” instead of “New Accepted”. Press Update.
6. Try navigating to the permalink of the post, and the Story should render but not as a valid AMP page; the Custom HTML markup should appear in the page, and the `html` element should have the `amp` attribute omitted.

# Before

image

Viewing the story:

image

# After

image

Viewing the story:

image

### CODE REVIEW

**Comment by kienstra** [comment]
**Approved**

Hi @westonruter,
This looks good! Great debugging on #3321.

Like you mentioned, I also saw that there were too many redirects when a validation error for a story was rejected:

too-many-redirects

But with this PR, the AMP story with the rejected error appears as expected:
amp-story-without-error

**Comment by swissspidy** [comment]
See issue description above for testing instructions

**Comment by csossi** [comment]
Warning message isn't appearing after "Publish"
image

But if I leave the story and return, then it appears:
image

**Comment by westonruter** [comment]
@csossi I was seeing this as well. However, I just tried in the latest 6.6.0-RC1 of Gutenberg, and I'm not seeing it. When creating a post or a story with invalid markup, it is showing me the warning upon the first save:

image

image

**Comment by swissspidy** [comment]
Verified this as per the testing instructions 👍

**Pull request merged**
