### PR TITLE
only show status on supported post types

### PR DESCRIPTION
**Pull request by paulschreiber**
Fixes the post metabox so AMP Status is not show on unsupported post types.

### CODE REVIEW

**Comment by westonruter** [comment]
Originally this was intentional in order to provide discovery for enabling the post types. But this was perhaps too “in your face”.

**Comment by paulschreiber** [comment]
Without this patch, you see the AMP enabled/disabled radio button on CPTs that aren't AMP-enabled (or aren't logically posts, such as custom page layouts). Clicking the "edit" link won't make that content available; it will instead show you a warning:
image

**Comment by westonruter** [comment]
Yes, that is what I meant was intentional.

**Comment by swissspidy** [comment]
I can see how this is confusing though. Is this shown only to admins or also other authors?

**Comment by westonruter** [comment]
Yeah, if we show it then it should be limited to admins.

**Comment by swissspidy** [comment]
Just checked, even contributors currently see that message.

@paulschreiber Would showing the message just for admins (users with `manage_options` capability) work for your environment?

**Comment by paulschreiber** [comment]
@swissspidy Showing the message only for admins is an improvement.

**Comment by swissspidy** [comment]
In addition to only showing for admins, I think it also should just be an info notice, not a warning. Or ideally, really not show anything.

I opened #2724 to discuss this more broadly.

**Comment by westonruter** [comment]
This will need to be re-factored to implement in the block editor. 

The PR also needs to target `develop`. So I'm going to close this PR in favor of opening a new issue to capture the full scope: #4593.

**Pull request closed without merging**
