### PR TITLE
Add fandom templates

### LINKED ISSUE #2426: Add additional templates to have 10 in total
AC: There are 5 Travel and 5 Fandom templates which can be inserted from the Template Inserter.

Add the following templates:
- Vertical (Travel) template -- this already has a .html file ready but it needs updating and adding to the import list.
- 5 templates for Fandom

See the templates here: https://projects.invisionapp.com/d/main#/projects/prototypes/17106855

### LINKED ISSUE #2436: How to index AMP pages and get AMP on the homepage
Hello, I have the AMP on lector mode and I want know how to have an AMP version of my homepage on [https://significadodelosgirasoles.ovh](https://significadodelosgirasoles.ovh). It can be possible? And how?

And, with the Google Search Console, I must put on the inspection tool the AMP's url? Or is better put just the original one?

Thanks.

### PR DESCRIPTION
**Pull request by miina**
Fixes #2426.

Adds Fandom templates.

Also reduces the size of assets used for templates.

### CODE REVIEW

**Comment by swissspidy** [comment]
Note that merge conflicts need to be resolved and the story template version needs to be increased as well.

**Comment by swissspidy** [comment]
By the way, @dawidmlynarz where are these photos from? We need to make sure the license allows using them.

**Comment by miina** [comment]
Yep, I'm waiting for #2472 to get merged, too, to update the colors for the Fandom CTA as well before resolving conflicts.

**Comment by dawidmlynarz** [comment]
@swissspidy Not sure about licensing since these are actual shots from the TV series - I suppose that this is the property of HBO in this case. Any ideas on how to get it as legal screenshots?

**Comment by miina** [comment]
@swissspidy The updates have been made to the CTA block now.

The only question now is about what to do with the images ...

@dawidmlynarz What about the Travel templates images? Are those purchased and licensed?

**Comment by swissspidy** [comment]
> What about the Travel templates images? Are those purchased and licensed?

IIRC they're from Unsplash

**Comment by kienstra** [comment]
**Looks Good**

Hi @miina,
Nice work, as usual. The "Fandom" templates look good:

fandom-templates

And of course the previous "Travel" templates also look good.

This isn't really a code question, but is it alright to have the "Game of Thrones" [logo](https://github.com/ampproject/amp-wp/pull/2479/files#diff-684f010745dfeab5d28c5ceeea059d6d) in the template?

got-logo

**Comment by miina** [comment]
Thanks for checking, @kienstra.

That's not the actual GoT logo, it's just a text created by Dawid with free Google font.

If that's OK to you and it looks good otherwise, please feel free to merge.

**Pull request merged**
