### PR TITLE
fix css margins for embeds

### PR DESCRIPTION
**Pull request by mostafaabd**
- i test it with YouTube, Instagram embed and its display full width screen, so i remove margin that break layout.

Fix issue #696

### CODE REVIEW

**Comment by westonruter** [comment]
Can you please add before/after screenshots?

Aside: This would only apply to Classic mode.

**Comment by mostafaabd** [comment]
i test it and its only apply to classic mode.
my opinion:  Its look good with margin before i submit PR, full width is perfect for Youtube video or Instagram embed  for small screen resolution.

**before** After text copying and pasting the Youtube video is full width screen

amp_before

**after:**

amp-after

**Comment by mostafaabd** [comment]
**Before:**

amp-2-before


**After:**

amp-2-after

**Comment by mostafaabd** [comment]
yes, its look nice with negative margin

**Pull request closed without merging**
