### PR TITLE
Stories main development branch

### PR DESCRIPTION
**Pull request by miina**
DO NOT MERGE!

## Summary

Please do not modify this branch directly, any changes should be done via PR-s.

## Checklist

- [ ] My pull request is addressing an [open issue](https://github.com/ampproject/amp-wp/contributing/project-management.md#life-of-an-issue) (please create one otherwise).
- [ ] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/contributing/engineering.md#tests).
- [ ] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/contributing/engineering.md) (updates are often made to the guidelines, check it out periodically).

### CODE REVIEW

**Comment by miina** [comment]
@barklund & @spacedmonkey Would you mind doing the "I consent" thing?

**Comment by barklund** [comment]
@googlebot I consent.

**Comment by spacedmonkey** [comment]
@googlebot I consent

**Comment by swissspidy** [comment]
Closing in favor of https://github.com/google/web-stories-wp/

Keeping the branch for now though.

**Pull request closed without merging**
