### PR TITLE
Use short array syntax throughout the project

### PR DESCRIPTION
**Pull request by swissspidy**
This is a bit of a follow-up to #2493.

The main plugin file, `amp.php`, is left untouched as it still should be parseable on PHP 5.2.

Also does not change `includes/sanitizers/class-amp-allowed-tags-generated.php` as it is auto-generated.

### CODE REVIEW

**Comment by westonruter** [comment]
As part of this, the PHPCS ruleset should be updated for force the preferred syntax for consistency.

**Comment by swissspidy** [comment]
Of course, good call!

**Comment by swissspidy** [comment]
The file is currently excluded from phpcs, and I left it out on purpose because it's auto-generated.

Fun Fact: PHPCS actually crashes locally for me because the file is so huge.

> I can update the generator to output the bracketed syntax as well.

Sounds good to me!

**Comment by westonruter** [comment]
> Fun Fact: PHPCS actually crashes locally for me because the file is so huge.

As part the plugin v2.0 effort, I'd like to revisit that file entirely, look at ways it can be made smaller and/or broken up into smaller files.

**Comment by swissspidy** [comment]
I was curious:

```
$ php -d memory_limit=4096M vendor/bin/phpcbf includes/sanitizers/class-amp-allowed-tags-generated.php

PHPCBF RESULT SUMMARY
-----------------------------------------------------------------------------
FILE                                                         FIXED  REMAINING
-----------------------------------------------------------------------------
includes/sanitizers/class-amp-allowed-tags-generated.php     15247  9
-----------------------------------------------------------------------------
A TOTAL OF 15247 ERRORS WERE FIXED IN 1 FILE
-----------------------------------------------------------------------------

Time: 1 mins, 60 secs; Memory: 12MB

```

😅😅😅

**Comment by westonruter** [comment]
/me shakes fist at Travis…

```
git diff develop...6bfa9746c7fb6c5c09a56667ff5c1c919c984901
fatal: Path 'amp.php' exists on disk, but not in '6bfa9746c7fb6c5
```

**Pull request merged**
