### PR TITLE
Adjust font-size in FE

### PR DESCRIPTION
**Pull request by miina**
Related: #2807

### CODE REVIEW

**Comment by swissspidy** [comment]
@miina Does this also work with amp-fit-text and manual font size overrides?

**Comment by miina** [comment]
It did at least when I was testing.

**Comment by swissspidy** [comment]
This addresses the issue that @csossi reported on Slack: https://xwp.slack.com/archives/CCCAUAH6F/p1563460594148700

**Comment by csossi** [comment]
Verified in QA

**Pull request merged**
