### PR TITLE
AMP Stories: The Next Iteration

### LINKED ISSUE #968: Implement AMP Stories
**ISSUE 1: As a WordPress author, I need to be able to manage content for AMP stories using Gutenberg.**
Key PR: #1215 

- [x] AC1: I should be able to create between 1 and _n_ pages for AMP stories.
   - [x] At this time, _n_ is assumed to be up to 20 pages (though this is not a hard limit).
- [x] AC2: I should be able to rearrange pages inside AMP stories.
- [x] AC3: I also, within each page, need to be able to create _x_ number of layers (CTA, grid layer, etc). 
   - [x] _x_ is assumed to be up to 5 layers at this point, but is not a hard limit.
   - [x] Only one CTA layer is allowed, and the interface should anticipate this.
- [ ] AC3: I should be able to rearrange layers inside AMP pages.
- [ ] AC4: Within each layer, I also need to be able to set layouts (thirds, fill, horizontal, vertical, etc.)
- [ ] AC5: Also within each layer, I need to be able to add my own blocks which are allowed by AMP (e.g. paragraph, image, video, etc).
- [ ] AC6: I should be able to preview the AMP story within the editor. I should also be able to edit each page next to each other. The current mode should be obvious to the author (edit or preview).
- [ ] AC7: I need a basic way to set default animations on pages, layers, elements for an AMP story.
- [ ] AC8: Each setting panel for each level (page, layer, element) should be clearly labeled as a user navigates through and selects them. There should be an intuitive way to be able to navigate through them. There should be an intuitive way to move items through layers if needed.
- [ ] AC9: I need a clear way to understand what I’ve selected is being edited. For example, a border or shading around an HTML element clearly shows a web browser console selecting that DOM element. 

# AMP Dependencies

- [ ] Expose lifecycle of AMP components to enable constructing them dynamically https://github.com/ampproject/amphtml/issues/17548

# Gutenberg Dependencies

- [x] Nested blocks (see https://github.com/WordPress/gutenberg/pull/3745 and [InnerBlocks](https://github.com/WordPress/gutenberg/blob/master/blocks/inner-blocks/README.md))
- [x] [Locked post type block templates](https://github.com/WordPress/gutenberg/blob/master/docs/templates.md#custom-post-types)
- [x] Restricting blocks to given post type: https://github.com/WordPress/gutenberg/pull/6208
- [x] Child blocks: https://github.com/WordPress/gutenberg/issues/5540
- [ ] Allow block to be constrained to only be used in root (when it has no parent): https://github.com/WordPress/gutenberg/issues/7845
- [ ] Default block, but only within a parent/outer block: https://github.com/WordPress/gutenberg/issues/7573
- [ ] Default Appender that is not Paragraph Based: https://github.com/WordPress/gutenberg/issues/8589
- [ ] Blocks: Consider a "passthrough" supports for nested block wrappers: https://github.com/WordPress/gutenberg/issues/7694
- [ ] Show block breadcrumbs for selected block when inline toolbars are enabled: https://github.com/WordPress/gutenberg/issues/6459
- [ ] Promote table of contents for navigation of nested blocks https://github.com/WordPress/gutenberg/issues/9053
- [x] Using dispatch( 'core/editor' ).selectBlock for a nested block focuses on its inner child instead: https://github.com/WordPress/gutenberg/issues/9212

# Resources

* [Search Engine Land coverage](https://searchengineland.com/amp-stories-new-accelerated-mobile-pages-format-google-291907)
* [AMP Story docs](https://www.ampproject.org/docs/reference/components/amp-story)
* [Example AMP Story from Washington Post](https://www.washingtonpost.com/graphics/2018/national/amp-stories/before-and-after-kilaueas-wrath-on-hawaiis-big-island/)

### PR DESCRIPTION
**Pull request by westonruter**
This PR squashes the commits from #1215 to serve as the basis for the beta iteration for AMP Stories. The code in the `amp-stories` branch reflects an alpha state of the feature which we'll now be iterating on as part of the [AMP Stories 1.0.0-beta project](https://github.com/ampproject/amp-wp/projects/10). The squashed commit allows us to start working with a clean PR and branch (`amp-stories-redux`) to merge sub-PRs into.

Shortlog of commit authors as part of squash of commits from PR #1215:

| Count | Author
|-------|-------
|   149	| Miina Sikk (@miina)
|    65	| Mike Crantea (@mehigh)
|    33	| Weston Ruter (@westonruter)
|    29	| Jacob Schweitzer (@jacobschweitzer)
|     4	| Shannon MacMillan (@bluestormcreative)

Fixes #968.

### CODE REVIEW

**Comment by westonruter** [comment]
@swissspidy Would you please merge `develop` back into this branch to resolve the merge conflicts?

**Comment by swissspidy** [comment]
@googlebot can you check again?

**Comment by swissspidy** [comment]
> (Googler, please make sure the reason for overriding the CLA status is clearly documented in these comments.)

There was a false positive because of a merge commit, which was done by `noreply@github.com`.

**Comment by swissspidy** [comment]
@googlebot Please re-check

**Pull request merged**
