### PR TITLE
Fix Text block's padding and related resizing issues

### LINKED ISSUE #2620: Lack of bottom padding on text block
Adding a Text block with a background color shows that there is an apparent lack of bottom padding:

image

Selecting text shows it going outside of its container:

image

This is not exhibited on the frontend:

image

This is the same whether fit-text is enabled or not.

### LINKED ISSUE #2629: Alignment not working for meta blocks when amp-fit-text Off
The alignment doesn't seem to be working for the following blocks:
- Author
- Title
- Date

Note that this happens only when amp-fit-text is turned off.

To reproduce:
- Create any of the blocks mentioned above.
- Turn "Automatically fit text to container" setting off.
- Try to align.

Screenshot 2019-06-14 at 12 40 57

### PR DESCRIPTION
**Pull request by miina**
Fixes #2620.

Aims to fix the following issues:
- Text content going over the edge of its wrapper.
- Resizing rotated Text block not working properly.

Also fixes #2629.

- Fixes aligning meta blocks in both the editor and on the frontend

### CODE REVIEW

**Comment by miina** [comment]
Note: Looks like quite a few regressions have occurred for the Text block, would probably be good to take a look afterward and see if there's a way how to simplify all this padding and border consideration.

**Comment by westonruter** [comment]
Just to note that this isn't fixing the issue yet in #2621. Upon loading the editor I see:

image

And when clicking to edit the block it adjusts:

image

**Comment by kienstra** [comment]
**Approved**

Hi @miina,
Nice work, as usual. This looks good.

It looks to fix the 2 points you [mentioned above](https://github.com/ampproject/amp-wp/pull/2624#issue-288145077):

>1. Text content going over the edge of its wrapper.

## Before
before-textblock


## After
after-textblock

>2. Resizing rotated Text block not working properly.

## Before

non-amp-fit-text

## After

after-no-empty-area


3. As @westonruter mentioned, I saw that the issue from #2621 still exists. That would have been a nice added bonus to fix that, but of course this doesn't say that it does 😄 

4. The 'Title,' 'Author,' and 'Date' blocks also rotate, resize, and drag well:

## Editor

editor-here

## Front-end

fe-here

**Comment by miina** [comment]
Unfortunately, just found a regression from this PR -- the text alignment doesn't seem to be working anymore for amp-fit-text... Continuing to look into this.

**Comment by swissspidy** [comment]
@miina Quick testing indicates adding the alignment on the wrapper would solve this.

**Comment by miina** [comment]
@swissspidy I tried that but for some reason this influences the font size -- if the alignment is to the right, the font size is much smaller. Does this happen for you as well?

**Comment by swissspidy** [comment]
I haven't noticed that, no.

But just to be clear: you're saying text alignment does not work when amp-fit-text is ON? In my testing it wasn't working when amp-fit-text is OFF.

**Comment by miina** [comment]
@swissspidy In my testing the alignment wasn't working in either of the cases eventually. Just added a fix that should fix that. I'll try again with the wrapper alignment, too.

On the font size changing: I could see that specifically with a very narrow (low height value) block -- the font size changed depending on the alignment. Not that this happened when testing modifying code, not within console.

**Comment by miina** [comment]
@swissspidy Looks like it happens when there is more than one word:
font-change

**Comment by miina** [comment]
@swissspidy Could you test again if it works better now?

**Comment by swissspidy** [comment]
I was testing with "Hello World" so far and haven't run into font size oddities when changing alignment.

**Comment by swissspidy** [comment]
While the meta blocks are now aligned in the editor, they don't appear to be aligned on the frontend.

Looks like they'd also need `display:block`, or at least not `display:flex` like `.wp-block-amp-amp-story-post-title` currently has by default.

**Comment by swissspidy** [comment]
Let's get this in and see if it holds up in testing 👍

**Pull request merged**
