### PR TITLE
Update WordPress packages

### PR DESCRIPTION
**Pull request by swissspidy**
## Summary

Fixes #4247
Fixes #4249
Fixes #4274

## Checklist

- [ ] My pull request is addressing an [open issue](https://github.com/ampproject/amp-wp/contributing/project-management.md#life-of-an-issue) (please create one otherwise).
- [ ] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/contributing/engineering.md#tests).
- [x] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/contributing/engineering.md) (updates are often made to the guidelines, check it out periodically).

### CODE REVIEW

**Comment by swissspidy** [comment]
Just like in #4247, the following test is failing:

```
1) Test_AMP_Theme_Support::test_filter_admin_bar_script_loader_tag with data set "admin_bar_scripts_have_dev_mode_with_paired_browsing_app" (Closure Object (...), Closure Object (...))
Expected element for query: //script[ contains( @src, "/amp-paired-browsing-app" ) ]
Failed asserting that null is an instance of class "DOMElement".
```

And I have no idea why. Any help appreciated.

**Comment by schlessera** [comment]
> And I have no idea why. Any help appreciated.

This is code that @pierlon has worked on, so he probably has an idea what the culprit might be.

**Comment by pierlon** [comment]
A quick guess would be one of the JS dependencies being missing on WP 4.9. I'll take a look into it.

**Comment by pierlon** [comment]
@googlebot I consent.

**Comment by pierlon** [comment]
Turns out `@wordpress/url` now requires `lodash` as a dependency. In https://github.com/ampproject/amp-wp/pull/4408/commits/c2fbf090a63065d5b8f5490d2d188c32b39701b6, I've copied lodash into the `assets/js/vendor` directory and register it as a WP dependency if it does not already exist.

**Comment by westonruter** [comment]
E2E tests keep [failing](https://travis-ci.org/github/ampproject/amp-wp/jobs/665008560#L875-L917) with:

```
 ● Featured Image Notice › should not display a notice, nor suggest cropping, when the image is the expected size
    TimeoutError: waiting for selector ".media-modal li[aria-label="e287a7d4-d2f7-411c-9d71-0c2a427dd99b"]" failed: timeout 3000ms exceeded
      36 | 
      37 | 	// Wait for upload.
    > 38 | 	await page.waitForSelector( `.media-modal li[aria-label="${ filename }"]` );
         | 	           ^
      39 | 
      40 | 	return fileWithExtension;
      41 | }
      at new WaitTask (../../node_modules/puppeteer/lib/DOMWorld.js:549:28)
      at DOMWorld._waitForSelectorOrXPath (../../node_modules/puppeteer/lib/DOMWorld.js:478:22)
      at DOMWorld.waitForSelector (../../node_modules/puppeteer/lib/DOMWorld.js:432:17)
      at Frame.waitForSelector (../../node_modules/puppeteer/lib/FrameManager.js:627:47)
      at Frame.<anonymous> (../../node_modules/puppeteer/lib/helper.js:112:23)
      at Page.waitForSelector (../../node_modules/puppeteer/lib/Page.js:1122:29)
      at waitForSelector (utils/upload-media.js:38:13)
          at runMicrotasks (<anonymous>)
      at Object.<anonymous> (specs/block-editor/featured-image-notice.js:30:3)
  ● Featured Image Notice › should display a notice when the image is too small, but not suggest cropping
    TimeoutError: waiting for selector ".media-modal li[aria-label="05f7c977-7766-423a-81f3-2a1ba256b1d5"]" failed: timeout 3000ms exceeded
      36 | 
      37 | 	// Wait for upload.
    > 38 | 	await page.waitForSelector( `.media-modal li[aria-label="${ filename }"]` );
         | 	           ^
      39 | 
      40 | 	return fileWithExtension;
      41 | }
      at new WaitTask (../../node_modules/puppeteer/lib/DOMWorld.js:549:28)
      at DOMWorld._waitForSelectorOrXPath (../../node_modules/puppeteer/lib/DOMWorld.js:478:22)
      at DOMWorld.waitForSelector (../../node_modules/puppeteer/lib/DOMWorld.js:432:17)
      at Frame.waitForSelector (../../node_modules/puppeteer/lib/FrameManager.js:627:47)
      at Frame.<anonymous> (../../node_modules/puppeteer/lib/helper.js:112:23)
      at Page.waitForSelector (../../node_modules/puppeteer/lib/Page.js:1122:29)
      at waitForSelector (utils/upload-media.js:38:13)
          at runMicrotasks (<anonymous>)
      at Object.<anonymous> (specs/block-editor/featured-image-notice.js:41:3)
```

**Comment by pierlon** [comment]
Turns out its a puppeteer issue (see https://github.com/WordPress/gutenberg/pull/20268 and https://github.com/puppeteer/puppeteer/issues/5420). 

We could wait for it to be fixed upstream, or use this patch to overcome the issue now:

```diff
Index: tests/e2e/utils/upload-media.js
<+>UTF-8
===================================================================
--- tests/e2e/utils/upload-media.js	(revision c2fbf090a63065d5b8f5490d2d188c32b39701b6)
+++ tests/e2e/utils/upload-media.js	(date 1584742106698)
@@ -24,8 +24,9 @@
 	const fileExtension = fileExtensionMatches[ 0 ];
 
 	// Wait for media modal to appear and upload video.
-	await page.waitForSelector( '.media-modal input[type=file]' );
-	const inputElement = await page.$( '.media-modal input[type=file]' );
+	const inputSelector = '.media-modal input[type=file]';
+	await page.waitForSelector( inputSelector );
+	const inputElement = await page.$( inputSelector );
 	const testMediaPath = path.join( __dirname, '..', 'assets', file );
 	const filename = uuidv4();
 
@@ -34,6 +35,10 @@
 	fs.copyFileSync( testMediaPath, tmpFileName );
 	await inputElement.uploadFile( tmpFileName );
 
+	await page.evaluate( ( input ) => {
+		document.querySelector( input ).dispatchEvent( new Event( 'change', { bubbles: true } ) );
+	}, inputSelector );
+
 	// Wait for upload.
 	await page.waitForSelector( `.media-modal li[aria-label="${ filename }"]` );
 
```

**Comment by westonruter** [comment]
I suppose it depends on WordPress 5.4… do these updates improve compatibility with 5.4 or are they more targeted for 5.5-alpha (aka current Gutenberg)? If the former, then let's do the patch. If the latter, then it can wait for 1.5.1.

**Comment by pierlon** [comment]
I'm not sure how these changes will improve compatibility with WordPress in anyways actually; I'm only aware of them affecting DX and and build process.

**Comment by westonruter** [comment]
OK, then this can wait for v1.5.1, unless @swissspidy sees differently. The puppeteer issue has been open for more than a month, so it doesn't look like it is getting resolved before 1.5.

**Comment by pierlon** [comment]
It seems there are only lint errors here to resolve. Would you want me to resolve them @swissspidy?

**Comment by swissspidy** [comment]
@pierlon sure, feel free!

**Pull request merged**
