### PR TITLE
Update min and max font sizes to match amp-fit-text

### PR DESCRIPTION
**Pull request by swissspidy**
Since amp-fit-text is also used in the regular block editor, it makes sense to use the same values in both environments.

See #2189.

### CODE REVIEW

**Comment by miina** [comment]
Hmm, for some reason I'm seeing 36 as the applied font size when resizing the author block large, can you confirm if you can see 72 as intended?

Screen Shot 2019-05-23 at 1 55 45 PM

**Comment by swissspidy** [comment]
Hmm `36` is the default value for `autoFontSize`, suggesting that the font size calculation is not running. Are there any errors in the console or something?

Also, I added some related changes in #2396. Can you try merging that branch into this one to see if this changes anything?

**Comment by miina** [comment]
Yep, looks like the font calculation is not working, for author and date block specifically.

**Comment by miina** [comment]
It might be because of the 100% height assigned -- we might need to remove that for the font calculation time.

**Comment by swissspidy** [comment]
It's even more trivial than that 🤦‍♂ See f07724d50e3030d0d6f2f615dbd9537a223a69f0

As for the `height: 100%`, we already remove it during calculation.

**Pull request merged**
