### PR TITLE
Improve handling of form submissions that redirect and implement form submission proxy

### LINKED ISSUE #4191: Support external POST forms via form submission proxy
Hi there!

I'm using the Genesis eNews Extended plugin to create a form and have my website visitors subscribe to my newsletter. I recently noticed that when I use AMP, the form does not work at all. I get an error message that says: "Your submission failed. The server responded with (code ). Please contact the developer of this form processor to improve this message. Learn More"

Do I need to add some headers or something to a filter in functions.php? Or is this a server issue?

Thanks!

### PR DESCRIPTION
**Pull request by westonruter**
## Summary

* Add support for automatically redirecting users when WordPress uses `header('Location: …')` in the same way as before `wp_redirect(…)` was able to automatically supply the `AMP-Redirect-To` response header. This should eliminate the need for [this shim code](https://gist.github.com/westonruter/b2554073461707a88057bb86b6b603d6#file-amp-gravity-form-submission-shim-php-L12-L29) in Gravity Forms. The corresponding [playbook information](https://amp-wp.org/documentation/playbooks/handling-form-submissions/) will also be obsolete with this PR.
* Add support for submitting forms to external domains by means of a new REST API form submission proxy. 

Fixes #4191.

Iterates on #2425. Revisits #911. See also #923.

## Testing

1. First of all, fire up [this Glitch to be able to test remote form submissions](https://glitch.com/~brook-paranthodon-k6ttvyw9a).
2. Then install the [Test POST Form](https://gist.github.com/westonruter/6c0eb253972ccdfc31f841629e2f4344) plugin.
3. Add two shortcodes to a post: `[test_post_form]` and `[test_post_form action="https://brook-paranthodon-k6ttvyw9a.glitch.me/"]`. For example:
```html
<!-- wp:paragraph -->
<p><strong>Internal action:</strong></p>
<!-- /wp:paragraph -->

<!-- wp:shortcode -->
[test_post_form]
<!-- /wp:shortcode -->

<!-- wp:paragraph -->
<p><strong>External action:</strong></p>
<!-- /wp:paragraph -->

<!-- wp:shortcode -->
[test_post_form action="https://brook-paranthodon-k6ttvyw9a.glitch.me/?foo=bar"]
<!-- /wp:shortcode -->
```
4. Check the behavior of submitting the internal action and external action forms when on an AMP page.

Any submission request type that has a JSON response (including the use of `wp_die()`) should have a response looking like:

image

or 

image

If the form handler does _not_ respond with something that can be represented as JSON (e.g. returning with an HTML page) then the expected output should look like:

image

or 

image

Note that the underlying HTTP status code and status text should be displayed in this message.

Additionally, if a form submission results in a redirect, either via `wp_redirect()` or using an underlying `header('Location: …')` call, then the user should be redirected after seeing a “Redirecting…” message momentarily:

image

Similar behavior should work both for when the form submission is handled internally by the present WordPress or if the form submission is pointing to another domain.

## Checklist

- [ ] My pull request is addressing an [open issue](https://github.com/ampproject/amp-wp/contributing/project-management.md#life-of-an-issue) (please create one otherwise).
- [ ] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/contributing/engineering.md#tests).
- [ ] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/contributing/engineering.md) (updates are often made to the guidelines, check it out periodically).

### CODE REVIEW

**Comment by westonruter** [comment]
Build for testing: [amp.zip](https://github.com/ampproject/amp-wp/files/4162433/amp.zip) (v1.5.0-alpha-20200205T225235Z-b246797c6)

**Comment by westonruter** [comment]
In testing making Genesis eNews Extended AMP-compatible in https://github.com/kraftbj/genesis-enews-extended/pull/146, I was trying to supply an `action-xhr` for the FeedBurner form as opposed to `action`:

```diff
diff --git a/class-bjgk-genesis-enews-extended.php b/class-bjgk-genesis-enews-extended.php
index 0dbce39..e3bf7d1 100644
--- a/class-bjgk-genesis-enews-extended.php
+++ b/class-bjgk-genesis-enews-extended.php
@@ -130,14 +130,15 @@ class BJGK_Genesis_ENews_Extended extends WP_Widget {
 		if ( ! empty( $instance['id'] ) ) : ?>
 			<form
 				id="subscribe-<?php echo esc_attr( $this->id ); ?>"
-				action="https://feedburner.google.com/fb/a/mailverify"
 				method="post"
 				name="<?php echo esc_attr( $this->id ); ?>"
 				<?php if ( ! $this->is_amp() ) : ?>
 					target="popupwindow"
 					onsubmit="window.open( 'https://feedburner.google.com/fb/a/mailverify?uri=<?php echo esc_js( $instance['id'] ); ?>', 'popupwindow', 'scrollbars=yes,width=550,height=520');return true"
+					action="https://feedburner.google.com/fb/a/mailverify"
 				<?php else: ?>
 					on="<?php echo esc_attr( sprintf( "submit-success:AMP.navigateTo( url=%s, target=_blank )", wp_json_encode( 'https://feedburner.google.com/fb/a/mailverify?uri=' . $instance['id'], JSON_UNESCAPED_SLASHES ) ) ); ?>"
+					action-xhr="https://feedburner.google.com/fb/a/mailverify"
 				<?php endif; ?>
 			>
 				<label for="subbox" class="screenread"><?php echo esc_attr( $instance['input_text'] ); ?></label><input type="<?php echo current_theme_supports( 'html5' ) ? 'email' : 'text'; ?>" value="" id="subbox" placeholder="<?php echo esc_attr( $instance['input_text'] ); ?>" name="email"
```

When I did this, however, I got an error in the console:

> Access to fetch at 'https://feedburner.google.com/fb/a/mailverify?__amp_source_origin=https%3A%2F%2Fwordpressdev.lndo.site' from origin 'https://wordpressdev.lndo.site' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

That brings something to mind. Should the proxy be prevented from relaying JSON if the proxied endpoint does not return `Access-Control-Allow-Origin`? The risk seems to be that an AMP page in WordPress could potentially request unauthorized endpoint on another domain. Nevertheless, since the proxy does not forward any cookies in the request (which wouldn't make sense anyway), this risk seems lessened. Nevertheless, if there is an auth key provided as a URL parameter then this could be an issue. 

I believe to harden this the proxy should be looking at any `Access-Control-Allow-Origin` and only allowing any JSON to pass through if the origin matches. Otherwise, since the proxy is on the same origin as the site, the access-control constraint would effectively be bypassed.

**Comment by chvillanuevap** [comment]
I just tested this version of the AMP plugin, and it worked great! I also tested the Genesis eNews Extended plugin and the `target="_blank"` bit worked as intended.

Thanks!

**Comment by natoinet** [comment]
Hi @westonruter,

Will it be released with AMP-wp v2.2 ? 
Or how can I add a Revue newsletter subscription form (using Revue Jetpack block) on a wordpress website running AMP-wp in standard mode ?

I've also been testing Jetpack Revue block along with AMP-wp v2.1.0-alpha-20210201T193527Z-cdfd29c.
While clicking on the subscribe button does not return an error anymore (while with AMP-wp v2.1, it was returning an error), the user is still not redirected to Revue after clicking on the Subscribe button.

Thanks :)

**Comment by westonruter** [comment]
@natoinet Yes, I want to finally get this into 2.2. This has been a long-standing pain point that needs to finally be addressed. I'll look at the Revue Block to see how it can be made compatible in the mean time.

**Comment by westonruter** [comment]
I've implemented an external form submission proxy for the AMP plugin in this mini plugin: https://gist.github.com/westonruter/c08134bf8b33a49ef780a70b337d456f

I tried testing it with Revue, however, and I wasn't having much luck. More testing is needed.

**Comment by westonruter** [comment]
The better bet here is going to be just allowing non-XHR POST forms on AMP pages. Without this, we have to resort to hacks. See https://github.com/ampproject/amphtml/issues/27638#issuecomment-853408150.

In the mean time, I hope my [mini plugin](https://gist.github.com/westonruter/c08134bf8b33a49ef780a70b337d456f) is useful as a workaround.

**Pull request closed without merging**
