### PR TITLE
[AMP Stories] Font Selection

### PR DESCRIPTION
**Pull request by swissspidy**
This PR extends current font selection with ~20 popular fonts from Google Fonts.

To do:

* [x] Maybe don't make font names translatable
* [x] Live previews
* [x] Use SVGs for font previews
* [x] Only enqueue fonts in the editor when selected
* [x] Load all used fonts when opening editor
* [x] Only enqueue needed fonts on the front end

See #1880.

### CODE REVIEW

**Comment by swissspidy** [comment]
> Only enqueue needed fonts on the front end

@westonruter Any tips on how to best do this? In the editor I simply go through all blocks with a font declaration and enqueue the stylesheet on the fly (0249e03c7ad8b60362f204aac42e271cb2903ba3). Not sure how to best approach on the front end though.

**Comment by westonruter** [comment]
Instead of defining all of these font families in CSS, let's instead define them in PHP like this:

```php
$font_families = array(
    'ubuntu' => array(
        'styles' => array( 'font-family' => "'Ubuntu',sans-serif"' )
    ),
);
```

Then with this data structure in hand, when we encounter a block that has the `data-font-family` attribute, we can then just-in-time enqueue the stylesheet from Google Fonts and then when PHP add an inline style to `amp-stories.php`:

```css
[data-font-family="ubuntu"] { font-family: 'Ubuntu',sans-serif }
```

This is important because the tree-shaker does not currently shake selectors like `[data-font-family="ubuntu"]`.

As for dynamic enqueueing, there are two different approaches we could take:

1. Register dynamic block `render_callback` functions for every block that that uses a `data-font-family` attribute. Enqueue the Google Font stylesheet `link` when generating the block, and the sanitizers will automatically move them to the `head`.
2. Rely more fully on the sanitizers by introducing a new sanitizer that will look for any element that has a `data-font-family` attribute and then dynamically generate the `link` element for the Google Font stylesheet and add it to the `head`, if one hasn't already been added. This would also be responsible for adding `style` elements with the corresponding `[data-font-family="…"]` rules.

The second approach is probably better.

@swissspidy I can work on this if you want.

**Comment by swissspidy** [comment]
Yes, that would be great! Thank you 🙂 

I was thinking of using `render_callback` for the page block already (#1899) so we don't have to worry about block deprecations. This might also be a good approach for the text block and easier to implement. However, I defer to you to make the decision.

**Comment by westonruter** [comment]
> I was thinking of using `render_callback` for the page block already

I think `render_callback` makes sense for the page, but it wouldn't be so clean to add a `render_callback` for every single block in a story page that has font controls.

**Comment by swissspidy** [comment]
True, although right now only the text block has font family controls (before it was paragraph + heading). But yeah, who knows how this might change in the future :-)

**Comment by westonruter** [comment]
Good point! I'll play around with what works better.

**Comment by westonruter** [comment]
@swissspidy Ready for your final review and merge!

**Pull request merged**
