### PR TITLE
If text has been pasted, also force update dimesisions.

### LINKED ISSUE #3291: Text block does not update height after pasting
## Bug Description

As reported in #3259:

See https://github.com/ampproject/amp-wp/pull/3259#issuecomment-532610932 for where this might be happening.

## Expected Behaviour

Pasting arbitrary text should create a new text block with correct height

## Steps to reproduce

1. Copy text from somewhere
1. Click on story page
1. Paste via keyboard
1. Notice how newly added text block does not update its height

## Screenshots

Screenshot from 2019-09-18 10-07-54

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Pasting arbitrary text should create a new text block with correct height

## Implementation brief

* Update `maybeUpdateBlockDimensions` so it correctly handles pasted blocks

## QA testing instructions

1. Copy text from somewhere
1. Click on story page
1. Paste via keyboard ( CTRL + V)
1. Verify height of text block is the height of the text.

## Demo

* https://youtu.be/X8i0Tb71QLc

## Changelog entry

* Improve calculating block dimensions when pasting text

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Summary

Fixes #3291

## Checklist

- [x] My pull request is addressing an [open issue](https://github.com/ampproject/amp-wp/contributing/project-management.md#life-of-an-issue) (please create one otherwise).
- [x] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/contributing/engineering.md#tests).
- [x] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/contributing/engineering.md) (updates are often made to the guidelines, check it out periodically).

### CODE REVIEW

**Comment by miina** [comment]
Looks like tests are failing, the same tests have failed previously as well, looks like these tests need looking into: https://travis-ci.org/ampproject/amp-wp/jobs/603942453#L922-L962

Rerunning the tests since these are unrelated to this PR.

**Comment by miina** [comment]
Hmm, I'm still seeing the issue:
issue

Could you confirm that you see it fixed?

**Comment by spacedmonkey** [comment]
@miina that is copying text into an existing text block. That is not the issue, all through that would be another issue. Look at the [testing instructions](https://github.com/ampproject/amp-wp/issues/3291#issuecomment-536610180).

Here is a video of it working for me - https://youtu.be/X8i0Tb71QLc

**Comment by miina** [comment]
Thanks for the clarification, somehow assumed that this would cover all the pasting issues! Will create a separate issue for pasting into an existing block then.

**Comment by miina** [comment]
Would you mind merging `develop` too?

**Comment by spacedmonkey** [comment]
> Would you mind merging `develop` too?

Go for it.

**Comment by miina** [comment]
@googlebot I consent.

**Comment by spacedmonkey** [comment]
I don't have access to merge PRs even if they are approved.

**Comment by miina** [comment]
I was asking if you would mind merging `develop` into this PR :) (Since you said "go for it", did it myself already, waiting for Travis now)

**Pull request merged**
