### PR TITLE
[AMP Stories] Fix: restore amp-story-page ID attribute

### PR DESCRIPTION
**Pull request by miina**

### CODE REVIEW

**Comment by miina** [comment]
`anchor` is used for animation order. I believe it's in use.

cc @swissspidy

**Comment by westonruter** [comment]
Maybe animation order can just use `id` instead of `anchor`?

**Comment by miina** [comment]
If I remember correctly then `anchor` is a general attribute name used for all the blocks, not just `amp-story-page`, however, probably @swissspidy can give more accurate information about `anchor` and its necessity for the `amp-story-page`.

**Comment by swissspidy** [comment]
Basically anchor is something that already exists in Gutenberg for the ID attribute, which is why I decided to reuse that.

**Comment by westonruter** [comment]
What about making the `amp-story-page` just indicate that the `anchor` prop is sourced to the `id` attribute? But wait, if Gutenberg is already using it for the `ID` attribute, then why is it not getting output? Do we just need to do:

```diff
- <amp-story-page style={ { backgroundColor: backgroundColor } } id={ id }>
+ <amp-story-page style={ { backgroundColor: backgroundColor } } id={ attributes.anchor }>
```

**Comment by swissspidy** [comment]
Haven‘t tested, but yeah probably it‘s as simple as that

**Pull request merged**
