### PR TITLE
Proposing amp_post_template_body_open hook (AMP Reader mode version of wp_body_open)

### PR DESCRIPTION
**Pull request by koconder**
Proposing a hook for post body, this will be part of an upcoming fix changes for third party analytics tracking tags and some A/B testing tools which require actions after opening body.

### CODE REVIEW

**Comment by westonruter** [comment]
Which such AMP components require placement as the first child of the `body`?

**Comment by westonruter** [comment]
It's not a requirement for [`amp-experiment`](https://www.ampproject.org/docs/reference/components/amp-experiment) or [`amp-analytics`](https://www.ampproject.org/docs/reference/components/amp-analytics).

**Comment by koconder** [comment]
@westonruter some analytics tools such as Google Tag Manager AMP requires injection of the amp-analytics post-body. I will source some more reliable information, as documentation is scarce.

**Comment by hkchakladar** [comment]
@westonruter So what's the hook available to insert auto-ads code?

**Comment by westonruter** [comment]
@hkchakladar For the legacy post templates embedded with the plugin, you can just use the `amp_post_template_footer ` action.

**Comment by koconder** [comment]
Reopening https://make.wordpress.org/themes/2019/03/29/addition-of-new-wp_body_open-hook/

**Comment by koconder** [comment]
Updated to use https://developer.wordpress.org/reference/hooks/wp_body_open/ instead as per the new wp_body_open() command

**Comment by koconder** [comment]
@westonruter i have pushed it back to where it originally was as amp_wp_body_open() - Let me know what we need in order to get this in, as wp_body_open() was much needed for some time and we need an AMP equivalent.

My original commit was using amp_post_template_body()

**Comment by koconder** [comment]
@westonruter any luck reviewing my comments above?

**Comment by westonruter** [comment]
I've updated the `amp-auto-ads` example plugin to make use of this new hook: https://gist.github.com/westonruter/a41573b932e24810b09949136b9a8445

**Comment by koconder** [comment]
Thanks @westonruter

**Pull request merged**
