### PR TITLE
Update wp-dev-lib package

### PR DESCRIPTION
**Pull request by pierlon**
See: xwp/wp-dev-lib/pull/310

## Checklist

- [ ] My pull request is addressing an [open issue](https://github.com/ampproject/amp-wp/contributing/project-management.md#life-of-an-issue) (please create one otherwise).
- [ ] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/contributing/engineering.md#tests).
- [ ] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/contributing/engineering.md) (updates are often made to the guidelines, check it out periodically).

### CODE REVIEW

**Comment by pierlon** [comment]
Ah wait a minute, pushing  an updated `composer.lock`.

**Comment by swissspidy** [comment]
Is this change worth it? Core has just fixed this for trunk: https://core.trac.wordpress.org/changeset/47048

**Comment by swissspidy** [comment]
There's some unrelated lint error now 🤔 

```
FILE: tests/php/test-class-amp-imgur-embed-handler.php
--------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
--------------------------------------------------------------------------------
 34 | ERROR | [x] Line indented incorrectly; expected at least 5 tabs, found
    |       |     4 (Generic.WhiteSpace.ScopeIndent.Incorrect)
--------------------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
--------------------------------------------------------------------------------
```

**Comment by pierlon** [comment]
> Is this change worth it?

Glad to see its fixed in Core. This package update would include the `wp-includes` folder from WP Core SVN which also includes the built block-library asset files, for example, so a win nonetheless.

**Comment by pierlon** [comment]
Reverted change from #3847 as the fix is now made upstream.

**Comment by westonruter** [comment]
The `test_prioritized_stylesheets` test is failing in WordPress 5.0 and 5.1.

**Pull request merged**
