### PR TITLE
Remove unused Travis deploy stage

### PR DESCRIPTION
**Pull request by westonruter**
We're currently not using the `ampconfdemo` environment for testing, which is what the current `deploy` stage is targeting. In any case, the limit of multidev environments on that site has been overrun doing deploys when pushing to the 1.3 branch currently causes a [failure](https://travis-ci.org/ampproject/amp-wp/builds/588979057):

image

So we should just eliminate the `deploy` stage and re-focus on getting automatic deployments to a testing environment set up. See #1840, #2084.

### CODE REVIEW

**Comment by schlessera** [comment]
The file `./bin/deploy-travis-pantheon.sh` is probably not needed anymore: https://github.com/ampproject/amp-wp/blob/0c627dc4be5085e00309f10970a38b0132fa40b1/bin/deploy-travis-pantheon.sh

Also, this cache folder referenced in `.travis.yml` can probably also be removed: https://github.com/ampproject/amp-wp/blob/0c627dc4be5085e00309f10970a38b0132fa40b1/.travis.yml#L25

**Comment by westonruter** [comment]
Good catch. Fixed in 1cc08e02.

**Comment by schlessera** [comment]
Seems good to go!

**Comment by westonruter** [comment]
Failed due to unrelated E2E test failure, so merging anyway.

**Pull request merged**
