### PR TITLE
(Temporarily) disable slow coverage jobs on Travis

### PR DESCRIPTION
**Pull request by swissspidy**

### CODE REVIEW

**Comment by westonruter** [comment]
The coverage job still shows taking 30 minutes:

image

**Comment by swissspidy** [comment]
The Travis config seems to be correct, but it just doesn't seem to work as expected 😕 

I guess for now we could just disable coverage for pull requests like this:

```diff
--- .travis.yml
+++ .travis.yml
@@ -110,7 +110,7 @@ jobs:
       env: WP_VERSION=trunk  DEV_LIB_ONLY=phpunit                               INSTALL_PWA_PLUGIN=1                        ALLOW_FAILURES=1
 
     - name: PHP and JavaScript unit tests (7.3, WordPress trunk, with code coverage)
-      if: branch = develop
+      if: branch = develop AND type = push
       php: "7.3"
       env: WP_VERSION=latest DEV_LIB_ONLY=phpunit                               INSTALL_PWA_PLUGIN=1 RUN_PHPUNIT_COVERAGE=1 ALLOW_FAILURES=1
       before_script:
```

**Comment by westonruter** [comment]
> I guess for now we could just disable coverage for pull requests like this:

I like that idea for the short term.

**Comment by westonruter** [comment]
FYI: Codecov badge support for wp-dev-lib proposed in https://github.com/xwp/wp-dev-lib/pull/299

**Comment by swissspidy** [comment]
No coverage reports for PRs now anymore: https://travis-ci.org/ampproject/amp-wp/builds/542669426. Not ideal, but as long as that is only temporary I can live with it.

**Pull request merged**
