### PR TITLE
Improve AMP preview button in WP 5.4 and with Gutenberg

### LINKED ISSUE #4368: AMP preview button looks off in WP 5.4-RC1
## Bug Description

The AMP preview button (introduced in #3323) which is available in Transitional and Reader modes, appears a bit off:

image

Hover state:

image

## Expected Behaviour

It should look rather like:

image

## Steps to reproduce

1. Activate Transitional or Reader mode.
2. Edit a post.
3. Look at Preview button and hover over it.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

### PR DESCRIPTION
**Pull request by kienstra**
## Summary
* Addresses the poor display of the AMP preview button that Weston found in https://github.com/ampproject/amp-wp/issues/4368#issue-577549011
* Use `<Button>` instead of the [now deprecated](https://github.com/WordPress/gutenberg/pull/19299/) `<IconButton>`
* Someone better at CSS might have better ideas. It's the best compromise of all of the scenarios
that I could come up with.
* Please also do `npm run build:css` for the changed styling here
* With this PR:

## 1) WP 5.3.2, Gutenberg plugin inactive (looks the same as WP 5.2)
button-5 3 2-no-gutenberg

## 2) WP 5.3.2, Gutenberg plugin active
button-5 3 2-with-gutenberg

## 3) WP 5.4-RC2, Gutenberg plugin inactive

button-5 4-no-gutenberg

## 4) WP 5.4-RC2, Gutenberg plugin active

button-5 4-with-gutenberg

Fixes #4368 

## Checklist

- [x] My pull request is addressing an [open issue](https://github.com/ampproject/amp-wp/contributing/project-management.md#life-of-an-issue) (please create one otherwise).
- [ ] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/contributing/engineering.md#tests). (Not tested, but there aren't component tests in the repo)
- [x] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/contributing/engineering.md) (updates are often made to the guidelines, check it out periodically).

### CODE REVIEW

**Comment by kienstra** [comment]
Hi @pierlon,
Could you please review this? Hope you had a great weekend 😄

**Comment by kienstra** [comment]
Sorry, forgot to remove the `DotTip`. But not planning on making more commits before a review.

**Comment by kienstra** [comment]
That should be all for commits, if/when Travis passes.

**Comment by kienstra** [comment]
Hi @pierlon,
Thanks a lot for reviewing this, great catch on the `<title>` showing `AMP-Icon`

**Comment by kienstra** [comment]
Here's the tooltip, good suggestion:

tooltip-here

**Comment by pierlon** [comment]
@googlebot I consent.

**Comment by kienstra** [comment]
OK, sounds good!

**Pull request merged**
