### PR TITLE
Remove changelog from readme

### PR DESCRIPTION
**Pull request by swissspidy**
See #1871.

### CODE REVIEW

**Comment by westonruter** [comment]
As part of this we'll also need to make sure there is GitHub release created with the changeling entries ported over.

**Comment by swissspidy** [comment]
The contributing guidelines currently refer to the changelog in the readme, recommending to update it before release:

https://github.com/ampproject/amp-wp/blob/bc59039bce8600fd4e98933e2c696cc038d5dfa3/contributing.md#creating-a-release

I suppose the separate changelog is easier to scan. For example, the 1.0.0 release only lists changes since 1.0.0 RC4, whereas the changelog lists them all together. That could be an argument for a separate `changelog.md` file.

**Comment by amedina** [comment]
I like the idea of separating the change log from the Readme. Wanted to do that prior to 1.0. Let's do it.

**Comment by westonruter** [comment]
> I suppose the separate changelog is easier to scan. For example, the 1.0.0 release only lists changes since 1.0.0 RC4, whereas the changelog lists them all together. That could be an argument for a separate `changelog.md` file.

And it's not easy to scan changes in https://github.com/ampproject/amp-wp/releases because of pre-releases?

> I like the idea of separating the change log from the Readme. Wanted to do that prior to 1.0. Let's do it.

Yeah, I wasn't aware at that time of the translation problem.

**Comment by swissspidy** [comment]
> And it's not easy to scan changes in [ampproject/amp-wp/releases](https://github.com/ampproject/amp-wp/releases) because of pre-releases?

IMO yes. A separate changelog file would be easier.

**Comment by westonruter** [comment]
Be there would be more maintenance burden. How about starting with just keeping changeling in GitHub releases only and then we evaluate a separate file later?

**Comment by swissspidy** [comment]
Maintenance would be the same as now, no? The changelog would just be in a different file. But yeah, let's evaluate that later.

**Comment by westonruter** [comment]
I mean, more maintenance than if we just keep the changeling entry in the GitHub release notes alone. Also, in release notes we don't have to make commits to edit them, which is nice.

**Comment by swissspidy** [comment]
@westonruter Updated `contributing.md` accordingly. What do you think?

**Pull request merged**
