### PR TITLE
Merge 1.0 release branch into master

### PR DESCRIPTION
**Pull request by kienstra**
This is step 11 of [Creating a Release](https://github.com/Automattic/amp-wp/blob/develop/contributing.md#creating-a-release):
>11. Merge release tag into master.

### CODE REVIEW

**Comment by kienstra** [comment]
**Request For Review**

Hi @amedina and @westonruter,
Here's a PR for you to sanity-check today if you have time, and merge tomorrow (Wednesday).

Thanks!

**Comment by kienstra** [comment]
This is a simple PR from the `1.0` branch to `master`. I haven't pushed anything straight to `1.0` for this.

**Comment by westonruter** [comment]
We can actually change this to merge from the `1.0.0` _tag_ instead of the `1.0` branch. Technically they'll be identical at this point, so it doesn't make much difference.

**Comment by kienstra** [comment]
>We can actually change this to merge from the 1.0.0 tag instead of the 1.0 branch. Technically they'll be identical at this point, so it doesn't make much difference.

Oh, good point.

**Pull request merged**
