### PR TITLE
Enforce stricter rules when linting React components

### PR DESCRIPTION
**Pull request by swissspidy**
* Enforce self-closing tags when there are no children
* Prevent unnecessary fragments
* Improve codee indentation
* Prevent unneeded prop types
* Prevent usage of unwrapped string literals

### CODE REVIEW

**Comment by miina** [comment]
Needs merging `develop` now.

Q: What does the `Prevent unneeded prop types` do? Does it mean that if the proptype is not actually present, it will display an error?

**Comment by swissspidy** [comment]
Yes, that's exactly what the [`react/no-unused-prop-types`](https://github.com/yannickcr/eslint-plugin-react/blob/c153a86f092c65e9fb01ee5ce544302b67f040de/docs/rules/no-unused-prop-types.md) rule does.

We could even go further and even [forbid vague prop types](https://github.com/yannickcr/eslint-plugin-react/blob/c153a86f092c65e9fb01ee5ce544302b67f040de/docs/rules/forbid-prop-types.md) with more specific alternatives available (`any`, `array`, `object`). However, that doesn't seem that useful at the moment.

**Comment by miina** [comment]
> Yes, that's exactly what the react/no-unused-prop-types rule does.

OK, that's great 👍

**Comment by swissspidy** [comment]
Resolved merge conflicts now

**Pull request merged**
