### PR TITLE
Add the Latest Stories data hook

### LINKED ISSUE #2300: Latest Stories Block: Missing CSS
When inserting the "Latest Stories" block, the block is completely unstyled:

Screenshot 2019-05-13 at 18 05 07

The CSS is added when saving and reloading the post:

Screenshot 2019-05-13 at 18 05 16

### PR DESCRIPTION
**Pull request by kienstra**
This simply uses `add_action()` to add the existing hook.

Fixes #2300

### CODE REVIEW

**Comment by kienstra** [comment]
**Request For Review**

Hi @swissspidy,
Hope you're doing great. Could you please review this when you can?

It [looks like](https://github.com/ampproject/amp-wp/issues/2300#issuecomment-494147158) the 'Latest Stories' block isn't available anymore.

This PR essentially reverts https://github.com/ampproject/amp-wp/pull/2338/commits/b21d6debdf04e5f71c51f74bf031ea50338df6c1, but maybe there's another reason for that commit.

At the moment, it doesn't look like `export_latest_stories_block_editor_data()` is referenced anywhere else, other than in a unit test.

Maybe it's intended to be called from within another method, not added as a hook.

Thanks, Pascal!

**Comment by swissspidy** [comment]
FWIW The issue with that hook/method is that it also runs on the story editor screen. There's just no output there because `amp-block-editor.js` is not enqueued in that scenario. Ideally that code would live in `AMP_Post_Meta_Box` to prevent this confusion.

**Comment by westonruter** [comment]
Otherwise, `export_latest_stories_block_editor_data` could have inside of it a check to see that the current post type is not `amp_story`?

**Comment by kienstra** [comment]
Sounds good, I could open a PR for that if you'd like.

**Comment by swissspidy** [comment]
@kienstra Thanks, that would be great.

**Comment by kienstra** [comment]
Sounds good, I'll do that now.

**Pull request merged**
