### PR TITLE
Fix reducing width for a Text block

### LINKED ISSUE #3396: Resizing smaller not possible than initial size for a rotated block (without amp-fit-text)
Steps to reproduce:
- Create a text block and turn amp-fit-text off.
- Rotate the block a little bit.
- Add some text inside it so that it would be on two lines at least.
- Resize the text from the bottom so that there would be enough room to resize it smaller from the side.
- Try resizing smaller from the side (e.g. right side).

resizing

Expected: As long as there is room for the text, it should be possible to resize it smaller from any side.

### PR DESCRIPTION
**Pull request by miina**
Fixes #3396

### CODE REVIEW

**Comment by miina** [comment]
Waiting for the tests to run to see if this might cause any regressions.

**Comment by miina** [comment]
@barklund Since it looks like you worked on a related issue (#3199) -- would you mind reviewing?

**Comment by barklund** [comment]
@googlebot I consent.

**Comment by swissspidy** [comment]
We have some e2e tests for resizing text blocks. One of them is actually skipped at the moment, see #3326.

Sounds like a good opportunity to add a test for this scenario here too.

**Comment by miina** [comment]
I was planning to add the tests (including looking into the skipped tests which are relevant) within #3397.

**Comment by swissspidy** [comment]
Works for me

**Pull request merged**
