### PR TITLE
Add video element

### LINKED ISSUE #3859: Video Element
## Feature description

Needs to come with support for automatically extracting the mandatory poster image from video if missing.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Summary

Fixes #3859

## Checklist

- [ ] My pull request is addressing an [open issue](https://github.com/ampproject/amp-wp/contributing/project-management.md#life-of-an-issue) (please create one otherwise).
- [ ] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/contributing/engineering.md#tests).
- [ ] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/contributing/engineering.md) (updates are often made to the guidelines, check it out periodically).

### CODE REVIEW

**Comment by spacedmonkey** [comment]
@googlebot I fixed it.

**Comment by miina** [comment]
This seems to currently be non-functional, just adding the element to the code, does it make sense to have it in its own PR if it's not usable? I suppose it doesn't make sense to add a placeholder either until it gets to Media Library.
Or are you still planning to make changes here since it's in Draft status currently?

**Comment by spacedmonkey** [comment]
We have 3 options here. 
1. Merge into `develop-stories` in current state.  It is not functional as it, but can be code reviewed in isolation. The media-library branch can be rebased / updated to include this new element and use it. 
2.  Merge `media-library` first and then change this to integrate with inserting from media library. 
3. Merge into `media-library`. This means that the media-library branch may get very big and code will get reviewed, but it keeps everything together. 

This PR is in draft, as the IB hasn't been written but I took it out of media-library branch and assigned you to review so you can look at it early. Thoughts @miina

**Comment by miina** [comment]
Either 1. or 3.
If we wouldn't add more features to the Media Library branch within the existing PR then it wouldn't grow too big. We could use that as a basis, merge, and iterate in other PRs. In this case, merging into `media-library` makes sense.

WDYT?

**Comment by spacedmonkey** [comment]
I would go for 1 and fix any issues with integration in `media-library`

**Comment by miina** [comment]
Sure, sounds good to me. The element will change quite a lot anyway later with the edit-display modes, so we can merge as-is once it's out of the Draft state to unblock the Media Library work.

**Comment by spacedmonkey** [comment]
@miina  I am still awaiting feedback on this [comment](https://github.com/ampproject/amp-wp/issues/3859#issuecomment-564606757). But it seems like we are not going to get a response quickly, so lets just merge this for now.

**Comment by miina** [comment]
OK, merging to unblock the Media Library.

@barklund Note: This PR will add a non-functional Video element for being able to use in the Media Library, feel free to ignore this in #3804, the design for Video editing isn't ready anyway + it won't be possible to actually add the element until it's in the Media Library.

**Pull request merged**
