### PR TITLE
Add/spa amp shadow dom updated with latest in develop

### PR DESCRIPTION
**Pull request by mehigh**
## Summary

Updated the spa-amp-shadow-dom branch with the latest in develop (8 files conflicted handled) and issued it against the branch part of this PR: https://github.com/ampproject/amp-wp/pull/1519 

I've fetched the latest from upstream and force pushed to match it:
https://github.com/xwp/amp-wp/

I've checked out locally the add/spa-amp-shadow-dom branch 
https://github.com/ampproject/amp-wp/pull/1519/files

I've pulled the latest in the develop branch and merged develop into this branch add/spa-amp-shadow-dom-updated using 3-way comparison to make sure nothing is missed.

## Checklist

- [x] My pull request is addressing an [open issue](https://github.com/ampproject/amp-wp/contributing/project-management.md#life-of-an-issue) (please create one otherwise).
- [ ] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/contributing/engineering.md#tests).
- [x] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/contributing/engineering.md) (updates are often made to the guidelines, check it out periodically).

### CODE REVIEW

**Comment by mehigh** [comment]
I'm OK with the contribution being committed to the project. I've responded to this before, noticed the googlebot asks again.
@indieisaconcept also hopes this goes through as well (we worked together on the project where this AMP fork is in use)

**Comment by westonruter** [comment]
@indieisaconcept I need your consent to merge this PR, specifically your authored commit 23ee679.

@mehigh Also, rather than merging this PR straight away I think it would be better to merge `develop` into the other branch on the ampproject repo and then this PR can just have the commits you added after resolving the conflicts.

**Comment by mehigh** [comment]
@westonruter I didn't have commit permissions to merge develop into the target branch in the ampproject repo. I did do exactly that first - fork it under xwp and do the develop merge to arrive at what's in this branch 5 commits prior. 
If you want me to reset this branch to only contain the develop 'merge' and send another PR with the 5 commits that I poured afterwards, I can do that. Is that better?

**Comment by westonruter** [comment]
@mehigh Yes, that would be good. Please either reset this branch to just have the merge commit that resolves the conflicts, and then have another one that adds the additional commits.

**Comment by mehigh** [comment]
Gotcha! I'll get that going.

**Comment by indieisaconcept** [comment]
@googlebot I consent

**Comment by mehigh** [comment]
@westonruter I've removed the 5 commits. This PR only contains the develop merge to this branch and handling of the conflicts.

**Comment by mehigh** [comment]
I created a separate PR with those 5 commits ^^. The diff there would decrease once this develop update is merged @westonruter

**Pull request merged**
