### PR TITLE
Fix console warning for SnapLines

### LINKED ISSUE #3462: snapLines prop accidentally passed to DOM elements
## Bug Description

After adding the snapping, it looks like the `snapLines` prop is accidentally passed to the underlying DOM elements. This causes a console warning:

## Expected Behaviour

No console warning.

## Steps to reproduce

1. Insert video block
2. See console warning

## Screenshots

Screenshot 2019-10-08 at 10 15 11

## Additional context

 - WordPress version: 5.3 Beta
 - Plugin version: current `develop`
 - Gutenberg plugin version (if applicable): 6.6
 - Browser: Chrome

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

### PR DESCRIPTION
**Pull request by spacedmonkey**
## Summary
Fixes #3462

## Checklist

- [ ] My pull request is addressing an [open issue](https://github.com/ampproject/amp-wp/contributing/project-management.md#life-of-an-issue) (please create one otherwise).
- [ ] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/contributing/engineering.md#tests).
- [ ] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/contributing/engineering.md) (updates are often made to the guidelines, check it out periodically).

### CODE REVIEW

**Comment by miina** [comment]
Based on a comment from @barklund (https://github.com/ampproject/amp-wp/issues/3458#issuecomment-540759386) then we might not need the `snapLines` in the context either if it's not used by any of the components (now when it's removed from `resizable-box`)

**Comment by spacedmonkey** [comment]
Thanks for the feedback @miina 

I have updated the PR so that snapLines are passed. It is a valid change and does fix the console error.

**Comment by miina** [comment]
Thanks for the update.

Hmm, it looks like removing the `snapLines` from `resizable-box` was reverted. Was that intentional, to add it back? Since `snapLines` is not part of the context anymore then it looks like it's always `undefined` in `resizable-box` and could also be removed, as you had it before. Thoughts?

**Comment by spacedmonkey** [comment]
> Hmm, it looks like removing the `snapLines` from `resizable-box` was reverted. Was that intentional, to add it back? Since `snapLines` is not part of the context anymore then it looks like it's always `undefined` in `resizable-box` and could also be removed, as you had it before. Thoughts?

 The first commit was removed and replaced with a second commit that fixes the issue as suggested. The current PR fixes the console warning. So can rereview as current commited change.

**Comment by miina** [comment]
> The first commit was removed and replaced with a second commit that fixes the issue as suggested. The current PR fixes the console warning. So can rereview as current commited change.

I understand, what I'm saying is that now when the `snapLines` is removed from the `context` then it can be removed from `resizable-box` as well. Since it's not passed down anymore then it's always `undefined` in the `resizable-box` anyway, it has become kind of a "left-over" there. Thoughts?

Or what was the reasoning for removing it from `context` but leaving it to `resizable-box`?

**Comment by spacedmonkey** [comment]
> I understand, what I'm saying is that now when the `snapLines` is removed from the `context` then it can be removed from `resizable-box` as well. Since it's not passed down anymore then it's always `undefined` in the `resizable-box` anyway, it has become kind of a "left-over" there. Thoughts?

Remove the snapLines from context, means that that prop is not passed down. When I console logged the props of `EnhancedResizableBox` see below.

```
ampFitText: undefined
angle: 0
blockName: "core/image"
children: {$$typeof: Symbol(react.element), key: null, ref: null, props: {…}, type: ƒ, …}
clearSnapLines: ƒ clearSnapLines()
clientId: "3742269e-c61a-4375-b5fd-095791049f28"
hasTextContent: false
height: 30
horizontalSnaps: ƒ (targetMin, targetMax)
minHeight: 30
minWidth: 40
onResizeStart: ƒ onResizeStart()
onResizeStop: ƒ onResizeStop(value)
parentBlockElement: div
setSnapLines: ƒ ()
snapGap: 8
verticalSnaps: ƒ (targetMin, targetMax)
width: 328
```

I can't see snapLines in there, so there is no need to remove it. Unless I am missing something.

**Comment by miina** [comment]
> Remove the snapLines from context, means that that prop is not passed down. When I console logged the props of EnhancedResizableBox see below.

Exactly!

> I can't see snapLines in there, so there is no need to remove it. Unless I am missing something.

But why leave it in to the code if it's always undefined (since it's not passed down) and it's not used at all in the component?

Why do this:
```
const {
			...
			snapLines,
                         ...
		} = otherProps;
```

for a variable that's always `undefined`? It's an extra line of code which doesn't seem to have any purpose at all. It would be the same as if adding a random undefined variable there -- it doesn't break the code but it's unnecessary.

Could you explain what would be the purpose of leaving it in, what is the benefit?

**Comment by spacedmonkey** [comment]
> Could you explain what would be the purpose of leaving it in, what is the benefit?

I haven't left it in? That line is not in the changelog. 

Screenshot from 2019-10-11 12-52-30

**Comment by miina** [comment]
Why am I seeing this locally in the PR when the local branch claims to be up to date 😕

Uh! If there's something wrong with the branch locally then I apologize for the confusing comments.

**Comment by miina** [comment]
Hmm, yep, there's something wrong with the local branch and it's not properly updating. I'm sorry for all the confusing comments, completely my bad!

**Pull request merged**
