### PR TITLE
Avoid undefined variable warning for $path_args which is populated by wp_parse_str()

### PR DESCRIPTION
**Pull request by paulschreiber**

### CODE REVIEW

**Comment by westonruter** [comment]
Can you provide details about how to reproduce the issue? What are the testing instructions?

**Comment by paulschreiber** [comment]
The WPVIP scanner displayed a warning about `$path_args` being undefined when we submitted AMP 1.2.0.

By code inspection, I see this is correct as `$path_args` isn't defined before use in `wp_parse_str()`.

**Comment by westonruter** [comment]
This is normal PHP, however, as the variable is passed by reference. For example, you will use a `$matches` variable when calling `preg_match()` without defining it beforehand.

**Comment by paulschreiber** [comment]
I define `$matches` beforehand. PHP's loose typing is letting you get away with something here, but it would be good to be more intentional / clearer about the code.

**Comment by swissspidy** [comment]
I think there are usually two types of positions in the PHP community about this. Personally I think it does not hurt at all to be explicit and to make the code more readable.

**Comment by westonruter** [comment]
@paulschreiber Is this the only place that WPVIP scanner raises a warning?

**Comment by swissspidy** [comment]
@westonruter Shouldn't this be merged into `develop` instead?

**Comment by westonruter** [comment]
Oops. I didn't see that. Yes.

**Comment by westonruter** [comment]
Bah. For simplicity I'll just cherry-pick the commit into `develop`.

**Comment by westonruter** [comment]
Or rather, a new cherry-pick PR into `develop`.

**Pull request merged**
