### PR TITLE
Fix dropzone by adding `key`

### LINKED ISSUE #3455: Dragging only possible after selecting page first
## Bug Description

When dragging one block then after that it's not possible to drag the other block. It displays the clone but dropping doesn't have any result. For being able to drag again, I first have to click the Page, and then drag the block.

## Expected Behaviour

After dragging one block, dragging another block should still be possible.

## Steps to reproduce

1. Add a block.
2. Add another block
3. Drag the first block.
4. Now try dragging the second block.
5. See the block not being dragged. It's possible to drag again after clicking on Page first.

## Screenshots

dragging

## Additional context

 N/A

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A user should be able to select a block within a page, independent of the page being manually selected, and move/drag the block.

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

### PR DESCRIPTION
**Pull request by miina**
## Summary

Fixes #3455 

Props @barklund 

## Checklist

- [x] My pull request is addressing an [open issue](https://github.com/ampproject/amp-wp/contributing/project-management.md#life-of-an-issue) (please create one otherwise).
- [ ] My code is tested and passes existing [tests](https://github.com/ampproject/amp-wp/contributing/engineering.md#tests).
- [x] My code follows the [Engineering Guidelines](https://github.com/ampproject/amp-wp/contributing/engineering.md) (updates are often made to the guidelines, check it out periodically).

### CODE REVIEW

**Comment by spacedmonkey** [comment]
@googlebot I consent.

**Comment by swissspidy** [comment]
@miina #3454 is a PR, but which _issue_ does this fix? :-)

Also, is this the right place to put the key? See https://reactjs.org/docs/lists-and-keys.html#extracting-components-with-keys

**Comment by swissspidy** [comment]
Looks like @barklund needs to ping the bot, as its his commit 🙂

**Comment by spacedmonkey** [comment]
> @miina #3454 is a PR, but which _issue_ does this fix? :-)

I have updated the PR to reference #3455

**Comment by miina** [comment]
@swissspidy See [this comment](https://xwp.slack.com/archives/CCCAUAH6F/p1570741689050200?thread_ts=1570711839.037200&cid=CCCAUAH6F) about adding the `key` (and the rest of the thread for context if you have time 😄 ).

**Comment by barklund** [comment]
@googlebot I consent.

**Pull request merged**
